= Cheatsheets

[[Http2PushMapping]]
== Http2PushMapping


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[extensionTarget]]`@extensionTarget`|`String`|-
|[[filePath]]`@filePath`|`String`|-
|[[noPush]]`@noPush`|`Boolean`|-
|===

[[SockJSBridgeOptions]]
== SockJSBridgeOptions

++++
 Options for configuring the event bus bridge.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[maxAddressLength]]`@maxAddressLength`|`Number (int)`|-
|[[maxHandlersPerSocket]]`@maxHandlersPerSocket`|`Number (int)`|-
|[[pingTimeout]]`@pingTimeout`|`Number (long)`|-
|[[replyTimeout]]`@replyTimeout`|`Number (long)`|-
|===

[[SockJSHandlerOptions]]
== SockJSHandlerOptions

++++
 Options for configuring a SockJS handler
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[disabledTransports]]`@disabledTransports`|`Array of String`|+++
Add a transport (by name) to the set of disabled transports.
+++
|[[heartbeatInterval]]`@heartbeatInterval`|`Number (long)`|+++
In order to keep proxies and load balancers from closing long running HTTP requests we need to pretend that the connection is active and send a heartbeat packet once in a while.
 This setting controls how often this is done.
 <p>
 Defaults to 25 seconds.
+++
|[[insertJSESSIONID]]`@insertJSESSIONID`|`Boolean`|+++
Whether to insert a <code>JSESSIONID</code> cookie so load-balancers ensure requests for a specific SockJS session are always routed to the correct server.
 <p>
 Defaults to <code>true</code>.
+++
|[[libraryURL]]`@libraryURL`|`String`|+++
Transports which don't support cross-domain communication natively use an iframe trick.
 A simple page is served from the SockJS server (using its foreign domain) and is placed in an invisible iframe.
 <p>
 Code run from this iframe doesn't need to worry about cross-domain issues, as it's being run from domain local to the SockJS server.
 This iframe also does need to load SockJS javascript client library, and this option lets you specify its URL.
+++
|[[localWriteHandler]]`@localWriteHandler`|`Boolean`|+++
Whether the <code>writeHandler</code> should be local only or cluster-wide.
 <p>
 Defaults to <code>true</code>.
+++
|[[maxBytesStreaming]]`@maxBytesStreaming`|`Number (int)`|+++
Most streaming transports save responses on the client side and don't free memory used by delivered messages.
 Such transports need to be garbage-collected once in a while.
 <p>
 This setting controls the maximum number of bytes that can be sent over a single HTTP streaming request before it will be closed.
 After that the client needs to open new request.
 Setting this value to one effectively disables streaming and will make streaming transports to behave like polling transports.
 <p>
 Defaults to 128K.
+++
|[[registerWriteHandler]]`@registerWriteHandler`|`Boolean`|+++
Whether a <code>writeHandler</code> should be registered on the link.
 <p>
 Defaults to <code>false</code>.
+++
|[[sessionTimeout]]`@sessionTimeout`|`Number (long)`|+++
Set the delay before the server sends a <code>close</code> event when a client receiving connection has not been seen for a while.
 <p>
 Defaults to 5 seconds.
+++
|===

