= Enums

[[ContainerSerializationStyle]]
== ContainerSerializationStyle

++++
 This enum contains supported object and arrays serialization styles. Every style has a enum value, and an array of
 strings to refeer to it.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[csv]]`csv`|
+++
Comma separated values: "value1,value2,value3"
 aliases: "csv", "commaDelimited", "form", "simple"
+++
|[[ssv]]`ssv`|
+++
Space separated values: "value1 value2 value3"
 aliases: "ssv", "spaceDelimited"
+++
|[[psv]]`psv`|
+++
Pipe separated values: "value1|value2|value3"
 aliases: "psv", "pipeDelimited"
+++
|[[dsv]]`dsv`|
+++
Dot delimited values: "value1.value2.value3"
 aliases: "dsv", "dotDelimited", "label"
+++
|[[simple_exploded_object]]`simple_exploded_object`|
+++
For internal usage, don't use it
+++
|[[matrix_exploded_array]]`matrix_exploded_array`|
+++
For internal usage, don't use it
+++
|===

[[ErrorType]]
== ErrorType

++++
 All errors type. You can get this values using link
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[NO_MATCH]]`NO_MATCH`|
+++
The provided value not match with ParameterTypeValidator rules
+++
|[[NOT_FOUND]]`NOT_FOUND`|
+++
Parameter not found in request
+++
|[[UNEXPECTED_ARRAY]]`UNEXPECTED_ARRAY`|
+++
It was expected a single value, but found in request an array
+++
|[[UNEXPECTED_SINGLE_STRING]]`UNEXPECTED_SINGLE_STRING`|
+++
It was expected an array, but found in request a single value
+++
|[[FILE_NOT_FOUND]]`FILE_NOT_FOUND`|
+++
Expected file not found
+++
|[[WRONG_CONTENT_TYPE]]`WRONG_CONTENT_TYPE`|
+++
Wrong Content-Type header
+++
|[[EMPTY_VALUE]]`EMPTY_VALUE`|
+++
Parameter found but with empty value
+++
|[[UNEXPECTED_ARRAY_SIZE]]`UNEXPECTED_ARRAY_SIZE`|
+++
Expected an array size between parameters configured in
 link
+++
|[[DESERIALIZATION_ERROR]]`DESERIALIZATION_ERROR`|
+++
Error during deserializaton with rule provided
+++
|[[OBJECT_FIELD_NOT_FOUND]]`OBJECT_FIELD_NOT_FOUND`|
+++
Object field declared as required in link not found
+++
|[[JSON_NOT_PARSABLE]]`JSON_NOT_PARSABLE`|
+++
Json can't be parsed
+++
|[[JSON_INVALID]]`JSON_INVALID`|
+++
Json doesn't match the provided schema
+++
|[[XML_INVALID]]`XML_INVALID`|
+++
XML doesn't match the provided schema
+++
|===

[[ContainerSerializationStyle]]
== ContainerSerializationStyle

++++
 This enum contains supported object and arrays serialization styles. Every style has a enum value, and an array of
 strings to refeer to it.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[csv]]`csv`|
+++
Comma separated values: "value1,value2,value3"
 aliases: "csv", "commaDelimited", "form", "simple"
+++
|[[ssv]]`ssv`|
+++
Space separated values: "value1 value2 value3"
 aliases: "ssv", "spaceDelimited"
+++
|[[psv]]`psv`|
+++
Pipe separated values: "value1|value2|value3"
 aliases: "psv", "pipeDelimited"
+++
|[[dsv]]`dsv`|
+++
Dot delimited values: "value1.value2.value3"
 aliases: "dsv", "dotDelimited", "label"
+++
|[[simple_exploded_object]]`simple_exploded_object`|
+++
For internal usage, don't use it
+++
|[[matrix_exploded_array]]`matrix_exploded_array`|
+++
For internal usage, don't use it
+++
|===

[[ErrorType]]
== ErrorType

++++
 All errors type. You can get this values using link
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[NO_MATCH]]`NO_MATCH`|
+++
The provided value not match with ParameterTypeValidator rules
+++
|[[NOT_FOUND]]`NOT_FOUND`|
+++
Parameter not found in request
+++
|[[UNEXPECTED_ARRAY]]`UNEXPECTED_ARRAY`|
+++
It was expected a single value, but found in request an array
+++
|[[UNEXPECTED_SINGLE_STRING]]`UNEXPECTED_SINGLE_STRING`|
+++
It was expected an array, but found in request a single value
+++
|[[FILE_NOT_FOUND]]`FILE_NOT_FOUND`|
+++
Expected file not found
+++
|[[WRONG_CONTENT_TYPE]]`WRONG_CONTENT_TYPE`|
+++
Wrong Content-Type header
+++
|[[EMPTY_VALUE]]`EMPTY_VALUE`|
+++
Parameter found but with empty value
+++
|[[UNEXPECTED_ARRAY_SIZE]]`UNEXPECTED_ARRAY_SIZE`|
+++
Expected an array size between parameters configured in
 link
+++
|[[DESERIALIZATION_ERROR]]`DESERIALIZATION_ERROR`|
+++
Error during deserializaton with rule provided
+++
|[[OBJECT_FIELD_NOT_FOUND]]`OBJECT_FIELD_NOT_FOUND`|
+++
Object field declared as required in link not found
+++
|[[JSON_NOT_PARSABLE]]`JSON_NOT_PARSABLE`|
+++
Json can't be parsed
+++
|[[JSON_INVALID]]`JSON_INVALID`|
+++
Json doesn't match the provided schema
+++
|[[XML_INVALID]]`XML_INVALID`|
+++
XML doesn't match the provided schema
+++
|===

[[LoggerFormat]]
== LoggerFormat

++++
 The possible out of the box formats.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[DEFAULT]]`DEFAULT`|
+++
<i>remote-client</i> - - [<i>timestamp</i>] "<i>method</i> <i>uri</i> <i>version</i>" <i>status</i> <i>content-length</i> "<i>referrer</i>" "<i>user-agent</i>"
+++
|[[SHORT]]`SHORT`|
+++
<i>remote-client</i> - <i>method</i> <i>uri</i> <i>version</i> <i>status</i> <i>content-length</i> <i>duration</i> ms
+++
|[[TINY]]`TINY`|
+++
<i>method</i> <i>uri</i> <i>status</i> - <i>content-length</i> <i>duration</i>
+++
|===

[[ParameterLocation]]
== ParameterLocation

++++
 ParameterLocation describe the location of parameter inside HTTP Request
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[HEADER]]`HEADER`|-
|[[QUERY]]`QUERY`|-
|[[PATH]]`PATH`|-
|[[FILE]]`FILE`|-
|[[BODY_FORM]]`BODY_FORM`|-
|[[BODY]]`BODY`|-
|[[BODY_JSON]]`BODY_JSON`|-
|[[BODY_XML]]`BODY_XML`|-
|[[COOKIE]]`COOKIE`|-
|===

[[ParameterType]]
== ParameterType

++++
 ParameterType contains prebuilt type validators. To access to ParameterTypeValidator of every ParameterType, use
 link
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[GENERIC_STRING]]`GENERIC_STRING`|
+++
STRING Type accept every string
+++
|[[EMAIL]]`EMAIL`|-
|[[URI]]`URI`|-
|[[BOOL]]`BOOL`|
+++
It allows true, false, t, f, 1, 0
+++
|[[INT]]`INT`|
+++
INT type does the validation with Integer.parseInt(value)
+++
|[[FLOAT]]`FLOAT`|
+++
FLOAT type does the validation with Float.parseFloat(value)
+++
|[[DOUBLE]]`DOUBLE`|
+++
DOUBLE type does the validation with Double.parseDouble(value)
+++
|[[DATE]]`DATE`|
+++
DATE as defined by full-date - RFC3339
+++
|[[DATETIME]]`DATETIME`|
+++
DATETIME as defined by date-time - RFC3339
+++
|[[TIME]]`TIME`|
+++
TIME as defined by partial-time - RFC3339
+++
|[[BASE64]]`BASE64`|-
|[[IPV4]]`IPV4`|-
|[[IPV6]]`IPV6`|-
|[[HOSTNAME]]`HOSTNAME`|-
|===

[[Transport]]
== Transport

++++
 The available SockJS transports
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[WEBSOCKET]]`WEBSOCKET`|
+++
<a href="http://www.rfc-editor.org/rfc/rfc6455.txt">rfc 6455</a>
+++
|[[EVENT_SOURCE]]`EVENT_SOURCE`|
+++
<a href="http://dev.w3.org/html5/eventsource/">Event source</a>
+++
|[[HTML_FILE]]`HTML_FILE`|
+++
<a href="http://cometdaily.com/2007/11/18/ie-activexhtmlfile-transport-part-ii/">HtmlFile</a>.
+++
|[[JSON_P]]`JSON_P`|
+++
Slow and old fashioned <a hred="https://developer.mozilla.org/en/DOM/window.postMessage">JSONP polling</a>.
 This transport will show "busy indicator" (aka: "spinning wheel") when sending data.
+++
|[[XHR]]`XHR`|
+++
Long-polling using <a hred="https://secure.wikimedia.org/wikipedia/en/wiki/XMLHttpRequest#Cross-domain_requests">cross domain XHR</a>
+++
|===

