= Enums

[[BridgeEventType]]
== BridgeEventType

++++
 Bridge Event Types.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[SOCKET_CREATED]]`SOCKET_CREATED`|
+++
This event will occur when a new SockJS socket is created.
+++
|[[SOCKET_CLOSED]]`SOCKET_CLOSED`|
+++
This event will occur when a SockJS socket is closed.
+++
|[[SOCKET_IDLE]]`SOCKET_IDLE`|
+++
This event will occur when SockJS socket is on idle for longer period of time than configured.
+++
|[[SOCKET_PING]]`SOCKET_PING`|
+++
This event will occur when the last ping timestamp is updated for the SockJS socket.
+++
|[[SEND]]`SEND`|
+++
This event will occur when a message is attempted to be sent from the client to the server.
+++
|[[PUBLISH]]`PUBLISH`|
+++
This event will occur when a message is attempted to be published from the client to the server.
+++
|[[RECEIVE]]`RECEIVE`|
+++
This event will occur when a message is attempted to be delivered from the server to the client.
+++
|[[REGISTER]]`REGISTER`|
+++
This event will occur when a client attempts to register a handler.
+++
|[[UNREGISTER]]`UNREGISTER`|
+++
This event will occur when a client attempts to unregister a handler.
+++
|===

[[LoggerFormat]]
== LoggerFormat

++++
 The possible out of the box formats.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[DEFAULT]]`DEFAULT`|
+++
<i>remote-client</i> - - [<i>timestamp</i>] "<i>method</i> <i>uri</i> <i>version</i>" <i>status</i> <i>content-length</i> "<i>referrer</i>" "<i>user-agent</i>"
+++
|[[SHORT]]`SHORT`|
+++
<i>remote-client</i> - <i>method</i> <i>uri</i> <i>version</i> <i>status</i> <i>content-length</i> <i>duration</i> ms
+++
|[[TINY]]`TINY`|
+++
<i>method</i> <i>uri</i> <i>status</i> - <i>content-length</i> <i>duration</i>
+++
|===

[[ParameterLocation]]
== ParameterLocation

++++
 ParameterLocation describe the location of parameter inside HTTP Request
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[HEADER]]`HEADER`|-
|[[QUERY]]`QUERY`|-
|[[PATH]]`PATH`|-
|[[FILE]]`FILE`|-
|[[BODY_FORM]]`BODY_FORM`|-
|[[BODY]]`BODY`|-
|[[BODY_JSON]]`BODY_JSON`|-
|[[BODY_XML]]`BODY_XML`|-
|[[COOKIE]]`COOKIE`|-
|===

[[ParameterType]]
== ParameterType

++++
 ParameterType contains prebuilt type validators. To access to ParameterTypeValidator of every ParameterType, use
 link
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[GENERIC_STRING]]`GENERIC_STRING`|
+++
STRING Type accept every string
+++
|[[EMAIL]]`EMAIL`|-
|[[URI]]`URI`|-
|[[BOOL]]`BOOL`|
+++
It allows true, false, t, f, 1, 0
+++
|[[INT]]`INT`|
+++
INT type does the validation with Integer.parseInt(value)
+++
|[[FLOAT]]`FLOAT`|
+++
FLOAT type does the validation with Float.parseFloat(value)
+++
|[[DOUBLE]]`DOUBLE`|
+++
DOUBLE type does the validation with Double.parseDouble(value)
+++
|[[DATE]]`DATE`|
+++
DATE as defined by full-date - RFC3339
+++
|[[DATETIME]]`DATETIME`|
+++
DATETIME as defined by date-time - RFC3339
+++
|[[TIME]]`TIME`|
+++
TIME as defined by partial-time - RFC3339
+++
|[[BASE64]]`BASE64`|-
|[[IPV4]]`IPV4`|-
|[[IPV6]]`IPV6`|-
|[[HOSTNAME]]`HOSTNAME`|-
|===

[[Transport]]
== Transport

++++
 The available SockJS transports
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[WEBSOCKET]]`WEBSOCKET`|
+++
<a href="http://www.rfc-editor.org/rfc/rfc6455.txt">rfc 6455</a>
+++
|[[EVENT_SOURCE]]`EVENT_SOURCE`|
+++
<a href="http://dev.w3.org/html5/eventsource/">Event source</a>
+++
|[[HTML_FILE]]`HTML_FILE`|
+++
<a href="http://cometdaily.com/2007/11/18/ie-activexhtmlfile-transport-part-ii/">HtmlFile</a>.
+++
|[[JSON_P]]`JSON_P`|
+++
Slow and old fashioned <a hred="https://developer.mozilla.org/en/DOM/window.postMessage">JSONP polling</a>.
 This transport will show "busy indicator" (aka: "spinning wheel") when sending data.
+++
|[[XHR]]`XHR`|
+++
Long-polling using <a hred="https://secure.wikimedia.org/wikipedia/en/wiki/XMLHttpRequest#Cross-domain_requests">cross domain XHR</a>
+++
|===

