= Cheatsheets

[[OpenAPILoaderOptions]]
== OpenAPILoaderOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[authHeaders]]`@authHeaders`|`String`|-
|[[authQueryParams]]`@authQueryParams`|`String`|-
|===

[[RouterBuilderOptions]]
== RouterBuilderOptions

++++
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[contractEndpoint]]`@contractEndpoint`|`String`|+++
Configures the endpoint where the contract is served.
 The contract is served using the
 <a href="https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.adoc#openapi-endpoint">Microprofile OpenAPI spec</a>.
+++
|[[mountNotImplementedHandler]]`@mountNotImplementedHandler`|`Boolean`|+++
If true, Router builder will automatically mount an handler that return HTTP 405/501 status code for each
 operation where you didn't specify an handler.
 You can customize the response with link
+++
|[[mountResponseContentTypeHandler]]`@mountResponseContentTypeHandler`|`Boolean`|+++
If true, when required, the factory will mount a link
+++
|[[operationModelKey]]`@operationModelKey`|`String`|+++
When set, an additional handler will be created to expose the operation model in the routing
 context under the given key. When the key is null, the handler is not added.
+++
|[[requireSecurityHandlers]]`@requireSecurityHandlers`|`Boolean`|+++
If true, when you call link ()} the factory will mount for every path
 the required security handlers and, if a security handler is not defined, it throws an
 link
+++
|[[routeNamingStrategy]]`@routeNamingStrategy`|`link:enums.html#RouteNamingStrategy[RouteNamingStrategy]`|+++
The strategy to follow when naming the generated routes.
+++
|===

