= Vert.x Web Client

Vert.x Web Client is an asynchronous HTTP / HTTP/2 client.

The Web Client makes easy to do HTTP request/response interactions with a web server, and provides advanced
features like:

* Json body encoding / decoding
* request/response pumping
* request parameters
* unified error handling

The web client does not deprecate the Vert.x Core `link:../../yardoc/Vertx/HttpClient.html[HttpClient]`, it is actually based on
it and therefore inherits its configuration and great features like pooling. The `link:../../yardoc/Vertx/HttpClient.html[HttpClient]`
should be used when fine grained control over the HTTP requests/response is necessary.

== Using the web client

To use Vert.x Web Client, add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-web-client</artifactId>
  <version>3.4.0-SNAPSHOT</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'io.vertx:vertx-web-client:3.4.0-SNAPSHOT'
}
----

== Re-cap on Vert.x core HTTP client

Vert.x Web Client uses the API from Vert.x core, so it's well worth getting familiar with the basic concepts of using
`link:../../yardoc/Vertx/HttpClient.html[HttpClient]` using Vert.x core, if you're not already.

== Creating a web client

You create an `link:../../yardoc/VertxWebClient/WebClient.html[WebClient]` instance with default options as follows

[source,java]
----
require 'vertx-web-client/web_client'
client = VertxWebClient::WebClient.create(vertx)

----

If you want to configure options for the client, you create it as follows

[source,java]
----
require 'vertx-web-client/web_client'
options = {
  'keepAlive' => false
}
client = VertxWebClient::WebClient.wrap(vertx.create_http_client(options))

----

== Making requests

=== Simple requests with no body

Often, you’ll want to make HTTP requests with no request body. This is usually the case with HTTP GET, OPTIONS
and HEAD requests

[source,java]
----
require 'vertx-web-client/web_client'

client = VertxWebClient::WebClient.create(vertx)

# Send a GET request
client.get(8080, "myserver.mycompany.com", "/some-uri").send() { |ar_err,ar|
  if (ar_err == nil)
    # Obtain response
    response = ar

    puts "Received response with status code#{response.status_code()}"
  else
    puts "Something went wrong #{ar_err.get_message()}"
  end
}

# Send a HEAD request
client.head(8080, "myserver.mycompany.com", "/some-uri").send() { |ar_err,ar|
  if (ar_err == nil)
    # Obtain response
    response = ar

    puts "Received response with status code#{response.status_code()}"
  else
    puts "Something went wrong #{ar_err.get_message()}"
  end
}

----

You can add query parameters to the request URI in a fluent fashion

[source,java]
----
Code not translatable
----

Any request URI parameter will pre-populate the request

[source,java]
----
request = client.get(8080, "myserver.mycompany.com", "/some-uri?param1=param1_value&param2=param2_value")

# Add param3
request.add_query_param("param3", "param3_value")

# Overwrite param2
request.set_query_param("param2", "another_param2_value")

----

=== Writing request bodies

When you need to make a request with a body, you use the same API and call then `sendXXX` methods
that expects a body to send.

Use `link:../../yardoc/VertxWebClient/HttpRequest.html#send_buffer-instance_method[sendBuffer]` to send a body buffer

[source,java]
----
# Send a buffer to the server using POST, the content-length header will be set for you
client.post(8080, "myserver.mycompany.com", "/some-uri").send_buffer(buffer) { |ar_err,ar|
  if (ar_err == nil)
    # Ok
  end
}

----

Sending a single buffer is useful but often you don't want to load fully the content in memory, for this
purpose the web client can send `ReadStream<Buffer>` (for example a `link:../../yardoc/Vertx/AsyncFile.html[AsyncFile]`
is a ReadStream<Buffer>`) with the `link:../../yardoc/VertxWebClient/HttpRequest.html#send_stream-instance_method[sendStream]` method

[source,java]
----
Code not translatable
----

The web client takes care of setting up the transfer Pump for you. The request will use chunked transfer
encoding as the length of the stream is not know.

When you know the size of the stream, you shall specify before using the `content-length` header

[source,java]
----
fs.open("content.txt", {
}) { |fileRes_err,fileRes|
  if (fileRes_err == nil)
    fileStream = fileRes

    fileLen = "1024"

    # Send the file to the server using POST
    client.post(8080, "myserver.mycompany.com", "/some-uri").put_header("content-length", fileLen).send_stream(fileStream) { |ar_err,ar|
      if (ar_err == nil)
        # Ok
      end
    }
  end
}

----

==== Json bodies

Often you’ll want to write requests which have a Json body. To send a `link:unavailable[JsonObject]`
use the `link:../../yardoc/VertxWebClient/HttpRequest.html#send_json_object-instance_method[sendJsonObject]`

[source,java]
----
client.post(8080, "myserver.mycompany.com", "/some-uri").send_json_object({
  'firstName' => "Dale",
  'lastName' => "Cooper"
}) { |ar_err,ar|
  if (ar_err == nil)
    # Ok
  end
}

----

In Java, Groovy or Kotlin, you can use the `link:../../yardoc/VertxWebClient/HttpRequest.html#send_json-instance_method[sendJson]` method that maps
a POJO (Plain Old Java Object) to a Json object using `link:unavailable#encode-class_method[Json.encode]`
method

[source,java]
----
client.post(8080, "myserver.mycompany.com", "/some-uri").send_json(Java::ExamplesWebClientExamples::User.new("Dale", "Cooper")) { |ar_err,ar|
  if (ar_err == nil)
    # Ok
  end
}

----

NOTE: the `link:unavailable#encode-class_method[Json.encode]` uses the Jackson mapper to encode the object
to Json.

=== Writing request headers

You can write headers to a request using the headers multi-map as follows:

[source,java]
----
request = client.get(8080, "myserver.mycompany.com", "/some-uri")
headers = request.headers()
headers.set("content-type", "application/json")
headers.set("other-header", "foo")

----

The headers are an instance of `link:../../yardoc/Vertx/MultiMap.html[MultiMap]` which provides operations for adding,
setting and removing entries. Http headers allow more than one value for a specific key.

You can also write headers using putHeader

[source,java]
----
request = client.get(8080, "myserver.mycompany.com", "/some-uri")
request.put_header("content-type", "application/json")
request.put_header("other-header", "foo")

----

=== Reusing requests

The `link:../../yardoc/VertxWebClient/HttpRequest.html#send-instance_method[send]` method can be called multiple times
safely, making it very easy to configure http requests and reuse them

[source,java]
----
get = client.get(8080, "myserver.mycompany.com", "/some-uri")
get.send() { |ar_err,ar|
  if (ar_err == nil)
    # Ok
  end
}

# Same request again
get.send() { |ar_err,ar|
  if (ar_err == nil)
    # Ok
  end
}

----

== Handling http responses

todo

=== Decoding responses

todo

=== RxJava API

The RxJava `link:unavailable[HttpRequest]` provides an rx-ified version of the original API,
the `link:unavailable#rx_send-instance_method[rxSend]` method returns a `Single<HttpResponse<Buffer>>` that
makes the HTTP request upon subscription, as consequence, the `Single` can be subscribed many times.

[source,java]
----
Code not translatable
----

The obtained `Single` can be composed and chained naturally with the RxJava API

[source,java]
----
Code not translatable
----