= Vert.x-Web API Contract
:toc: left

Vert.x-Web API Contract brings to Vert.x two features to help you to develop you API:

* HTTP Requests validation
* OpenAPI 3 Support with automatic requests validation

== Using Vert.x API Contract

To use Vert.x API Contract, add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-web-api-contract</artifactId>
  <version>3.5.1-SNAPSHOT</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'io.vertx:vertx-web-api-contract:3.5.1-SNAPSHOT'
}
----

== HTTP Requests validation

Vert.x provides a validation framework that will validate requests for you and will put results of validation inside a container.

To define a `link:../../jsdoc/module-vertx-web-api-contract-js_http_request_validation_handler-HTTPRequestValidationHandler.html[HTTPRequestValidationHandler]`:

[source,js]
----
var HTTPRequestValidationHandler = require("vertx-web-api-contract-js/http_request_validation_handler");
// Create Validation Handler with some stuff
var validationHandler = HTTPRequestValidationHandler.create().addQueryParam("parameterName", 'INT', true).addFormParamWithPattern("formParameterName", "a{4}", true).addPathParam("pathParam", 'FLOAT');

----

Then you can mount your validation handler:

[source,js]
----
var BodyHandler = require("vertx-web-js/body_handler");
// BodyHandler is required to manage body parameters like forms or json body
router.route().handler(BodyHandler.create().handle);

router.get("/awesome/:pathParam").handler(validationHandler.handle).handler(function (routingContext) {
  // Get Request parameters container
  var params = routingContext.get("parsedParameters");

  // Get parameters
  var parameterName = params.queryParameter("parameterName").getInteger();
  var formParameterName = params.formParameter("formParameterName").getString();
  var pathParam = params.pathParameter("pathParam").getFloat();
}).failureHandler(function (routingContext) {
  var failure = routingContext.failure();
  if (failure.getClass().getSimpleName() == 'ValidationException') {
    // Something went wrong during validation!
    var validationErrorMessage = failure.getMessage();
  }
});

----

If validation succeeds, It returns request parameters inside `link:../../jsdoc/module-vertx-web-api-contract-js_request_parameters-RequestParameters.html[RequestParameters]`, otherwise It will throw a `ValidationException`

=== Types of request parameters
Every parameter has a type validator, a class that describes the expected type of parameter.
A type validator validates the value, casts it in required language type and then loads it inside a `link:../../jsdoc/module-vertx-web-api-contract-js_request_parameter-RequestParameter.html[RequestParameter]` object. There are three ways to describe the type of your parameter:

* There is a set of prebuilt types that you can use: `link:../enums.html#ParameterType[ParameterType]`
* You can instantiate a custom instance of prebuilt type validators using static methods of `link:../../jsdoc/module-vertx-web-api-contract-js_parameter_type_validator-ParameterTypeValidator.html[ParameterTypeValidator]` and then load it into `link:../../jsdoc/module-vertx-web-api-contract-js_http_request_validation_handler-HTTPRequestValidationHandler.html[HTTPRequestValidationHandler]` using functions ending with `WithCustomTypeValidator`
* You can create your own `ParameterTypeValidator` implementing `link:../../jsdoc/module-vertx-web-api-contract-js_parameter_type_validator-ParameterTypeValidator.html[ParameterTypeValidator]` interface

=== Handling parameters
Now you can handle parameter values:

[source,js]
----
var params = routingContext.get("parsedParameters");
var awesomeParameter = params.queryParameter("awesomeParameter");
if ((awesomeParameter !== null && awesomeParameter !== undefined)) {
  if (!awesomeParameter.isEmpty()) {
    // Parameter exists and isn't empty
    // ParameterTypeValidator mapped the parameter in equivalent language object
    var awesome = awesomeParameter.getInteger();
  } else {
    // Parameter exists, but it's empty
  }
} else {
  // Parameter doesn't exist (it's not required)
}

----

As you can see, every parameter is mapped in respective language objects. You can also get a json body:

[source,js]
----
var body = params.body();
if ((body !== null && body !== undefined)) {
  var jsonBody = body.getJsonObject();
}

----

== OpenAPI 3 support

Vert.x allows you to use your OpenApi 3 specification directly inside your code using the design first approach. Vert.x-Web provides:

* OpenAPI 3 compliant API specification validation with automatic **loading of external Json schemas**
* Automatic request validation
* Automatic mount of security validation handlers
* Automatic 501 response for not implemented operations
* Router factory to provide all these features to users

You can also use the community project https://github.com/pmlopes/slush-vertx[`slush-vertx`] to generate server code from your OpenAPI 3 specification.

=== The router factory
You can create your web service based on OpenAPI3 specification with `link:../../jsdoc/module-vertx-web-api-contract-js_open_api3_router_factory-OpenAPI3RouterFactory.html[OpenAPI3RouterFactory]`.
This class, as name says, is a router factory based on your OpenAPI 3 specification.
`link:../../jsdoc/module-vertx-web-api-contract-js_open_api3_router_factory-OpenAPI3RouterFactory.html[OpenAPI3RouterFactory]` is intended to give you a really simple user interface to use OpenAPI 3 support. It includes:

* Async loading of specification and its schema dependencies
* Mount path with operationId or with combination of path and HTTP method
* Automatic request parameters validation
* Automatic convert OpenAPI style paths to Vert.x style paths
* Lazy methods: operations (combination of paths and HTTP methods) are mounted in declaration order inside specification
* Automatic mount of security validation handlers

=== Create a new router factory
To create a new router factory, Use method `link:../../jsdoc/module-vertx-web-api-contract-js_open_api3_router_factory-OpenAPI3RouterFactory.html#create[OpenAPI3RouterFactory.create]`.
As location It accepts absolute paths, local paths and local or remote URLs (HTTP or file protocol).

For example:

[source,js]
----
var OpenAPI3RouterFactory = require("vertx-web-api-contract-js/open_api3_router_factory");
OpenAPI3RouterFactory.create(vertx, "src/main/resources/petstore.yaml", function (ar, ar_err) {
  if (ar_err == null) {
    // Spec loaded with success
    var routerFactory = ar;
  } else {
    // Something went wrong during router factory initialization
    var exception = ar_err;
  }
});

----

You can also construct a router factory from a remote spec:

[source,js]
----
var OpenAPI3RouterFactory = require("vertx-web-api-contract-js/open_api3_router_factory");
OpenAPI3RouterFactory.create(vertx, "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml", function (ar, ar_err) {
  if (ar_err == null) {
    // Spec loaded with success
    var routerFactory = ar;
  } else {
    // Something went wrong during router factory initialization
    var exception = ar_err;
  }
});

----

You can also modify the behaviours of the router factory with `link:../dataobjects.html#RouterFactoryOptions[RouterFactoryOptions]`.
For example you can ask to router factory to mount the validation failure handler but to not mount the not implemented handler as follows:

[source,js]
----
var routerFactory = ar.result();
// Create and mount options to router factory
var options = {
  "mountNotImplementedHandler" : true,
  "mountValidationFailureHandler" : false
};

routerFactory.setOptions(options);

----

=== Mount the handlers
Now load your first path. There are two functions to load the handlers:

* `link:../../jsdoc/module-vertx-web-api-contract-js_router_factory-RouterFactory.html#addHandler[addHandler]`
* `link:../../jsdoc/module-vertx-web-api-contract-js_open_api3_router_factory-OpenAPI3RouterFactory.html#addHandlerByOperationId[addHandlerByOperationId]`

And, of course, two functions to load failure handlers

* `link:../../jsdoc/module-vertx-web-api-contract-js_router_factory-RouterFactory.html#addFailureHandler[addFailureHandler]`
* `link:../../jsdoc/module-vertx-web-api-contract-js_open_api3_router_factory-OpenAPI3RouterFactory.html#addFailureHandlerByOperationId[addFailureHandlerByOperationId]`

You can, of course, **add multiple handlers to same operation**, without overwrite the existing ones.

.Path in OpenAPI format
IMPORTANT: If you want to use `link:../../jsdoc/module-vertx-web-api-contract-js_router_factory-RouterFactory.html#addHandler[addHandler]` or `link:../../jsdoc/module-vertx-web-api-contract-js_router_factory-RouterFactory.html#addFailureHandler[addFailureHandler]` pay attention: You can provide a path only in OpenAPI styles (for example path `/hello/:param` doesn't work)

For example:

[source,js]
----
routerFactory.addHandlerByOperationId("awesomeOperation", function (routingContext) {
  var params = routingContext.get("parsedParameters");
  var body = params.body();
  var jsonBody = body.getJsonObject();
  // Do something with body
});
routerFactory.addFailureHandlerByOperationId("awesomeOperation", function (routingContext) {
  // Handle failure
});

----

.Add operations with operationId
IMPORTANT: Usage of combination of path and HTTP method is allowed, but it's better to add operations handlers with operationId, for performance reasons and to avoid paths nomenclature errors

Now you can use parameter values as described above

== Define security handlers
A security handler is defined by a combination of schema name and scope. You can mount only one security handler for a combination.
For example:

[source,js]
----
routerFactory.addSecurityHandler("security_scheme_name", securityHandler);

----

You can of course use included Vert.x security handlers, for example:

[source,js]
----
var JWTAuthHandler = require("vertx-web-js/jwt_auth_handler");
routerFactory.addSecurityHandler("jwt_auth", JWTAuthHandler.create(jwtAuthProvider).handle);

----

=== Customize the router factory behaviours
The router factory allows you to customize some behaviours during router generation with
`link:../dataobjects.html#RouterFactoryOptions[RouterFactoryOptions]`. Router factory can:

* Mount a 501 `Not Implemented` handler for operations where you haven't mounted any handler
* Mount a 400 `Bad Request` handler that manages `ValidationException`
* Mount the `link:../../jsdoc/module-vertx-web-js_response_content_type_handler-ResponseContentTypeHandler.html[ResponseContentTypeHandler]` handler when needed

Give a deeper look at `link:../dataobjects.html#RouterFactoryOptions[RouterFactoryOptions]` documentation

=== Generate the router
When you are ready, generate the router and use it:

[source,js]
----
var router = routerFactory.getRouter();

var server = vertx.createHttpServer({
  "port" : 8080,
  "host" : "localhost"
});
server.requestHandler(router.accept).listen();

----