= Vert.x-Web API Contract
:toc: left

== OpenAPI 3 support

Vert.x allows you to use your OpenApi 3 specification directly inside your code using the design first approach.

Vert.x-Web provides:

* OpenAPI 3 compliant API specification validation with automatic **loading of external Json schemas**
* Automatic request validation
* Automatic mount of security validation handlers
* Automatic 501 response for not implemented operations
* Router factory to provide all these features to users

=== The router factory
You can create your web service based on OpenAPI3 specification with `link:../../jsdoc/module-vertx-web-api-contract-js_open_api3_router_factory-OpenAPI3RouterFactory.html[OpenAPI3RouterFactory]`.
This class, as name says, is a router factory based on your OpenAPI 3 specification.
`link:../../jsdoc/module-vertx-web-api-contract-js_open_api3_router_factory-OpenAPI3RouterFactory.html[OpenAPI3RouterFactory]` is intended to give you a really simple user interface to use OpenAPI 3 support. It includes:

* Async loading of specification and its schema dependencies
* Mount path with operationId or with combination of path and HTTP method
* Automatic request parameters validation
* Automatic convert OpenAPI style paths to Vert.x style paths
* Lazy methods: operations (combination of paths and HTTP methods) are mounted in declaration order inside specification
* Automatic mount of security validation handlers

=== Create a new router factory
To create a new router factory, you can use methods inside `link:../../jsdoc/module-vertx-web-api-contract-js_open_api3_router_factory-OpenAPI3RouterFactory.html[OpenAPI3RouterFactory]`:

* `link:../../jsdoc/module-vertx-web-api-contract-js_open_api3_router_factory-OpenAPI3RouterFactory.html#createRouterFactoryFromFile[OpenAPI3RouterFactory.createRouterFactoryFromFile]`  to create a router factory from local file
* `link:../../jsdoc/module-vertx-web-api-contract-js_open_api3_router_factory-OpenAPI3RouterFactory.html#createRouterFactoryFromURL[OpenAPI3RouterFactory.createRouterFactoryFromURL]`  to create a router factory from url

For example:
[source,js]
----
`constructRouterFactory`
----

=== Mount the handlers
Now load your first path. There are two functions to load the handlers:

* `link:../../jsdoc/module-vertx-web-api-contract-js_design_driven_router_factory-DesignDrivenRouterFactory.html#addHandler[addHandler]`
* `link:../../jsdoc/module-vertx-web-api-contract-js_open_api3_router_factory-OpenAPI3RouterFactory.html#addHandlerByOperationId[addHandlerByOperationId]`

And, of course, two functions to load failure handlers

* `link:../../jsdoc/module-vertx-web-api-contract-js_design_driven_router_factory-DesignDrivenRouterFactory.html#addFailureHandler[addFailureHandler]`
* `link:../../jsdoc/module-vertx-web-api-contract-js_open_api3_router_factory-OpenAPI3RouterFactory.html#addFailureHandlerByOperationId[addFailureHandlerByOperationId]`

You can, of course, **add multiple handlers to same operation**, without overwrite the existing ones.

.Path in OpenAPI format
IMPORTANT: If you want to use `link:../../jsdoc/module-vertx-web-api-contract-js_design_driven_router_factory-DesignDrivenRouterFactory.html#addHandler[addHandler]` or `link:../../jsdoc/module-vertx-web-api-contract-js_design_driven_router_factory-DesignDrivenRouterFactory.html#addFailureHandler[addFailureHandler]` pay attention: You can provide a path only in OpenAPI styles (for example path `/hello/:param` doesn't work)

For example:
[source,js]
----
`addRoute`
----

.Add operations with operationId
IMPORTANT: Usage of combination of path and HTTP method is allowed, but it's better to add operations handlers with operationId, for performance reasons and to avoid paths nomenclature errors

Now you can use parameter values as described in http://vertx.io/docs/vertx-web/java/#_andling_parameters[vertx-web documentation]

== Define security handlers
A security handler is defined by a combination of schema name and scope. You can mount only one security handler for a combination.
For example:

[source,js]
----
`addSecurityHandler`
----

You can of course use included Vert.x security handlers, for example:

[source,js]
----
`addJWT`
----

=== Error handling
The router factory allows you to manage errors efficiently:

* It automatically mounts a 501 `Not Implemented` handler for operations where you haven't mounted any handler
* It automatically mounts a 400 `Bad Request` handler that manages `ValidationException` (You can enable/disable this feature via `link:../../jsdoc/module-vertx-web-api-contract-js_design_driven_router_factory-DesignDrivenRouterFactory.html#enableValidationFailureHandler[enableValidationFailureHandler]`)

=== Generate the router
When you are ready, generate the router and use it:

[source,js]
----
`generateRouter`
----

== Requests validation

Vert.x provides a validation framework that will validate requests for you and will put results of validation inside a container. To define a `link:../../jsdoc/module-vertx-web-api-contract-js_http_request_validation_handler-HTTPRequestValidationHandler.html[HTTPRequestValidationHandler]`:
[source,js]
----
`example63`
----

Then you can mount your validation handler:
[source,js]
----
`example64`
----

If validation succeeds, It returns request parameters inside `link:../../jsdoc/module-vertx-web-api-contract-js_request_parameters-RequestParameters.html[RequestParameters]`, otherwise It will throw a `ValidationException`

=== Types of request parameters
Every parameter has a type validator, a class that describes the expected type of parameter.
A type validator validates the value, casts it in required language type and then loads it inside a `link:../../jsdoc/module-vertx-web-api-contract-js_request_parameter-RequestParameter.html[RequestParameter]` object. There are three ways to describe the type of your parameter:

* There is a set of prebuilt types that you can use: `link:../enums.html#ParameterType[ParameterType]`
* You can instantiate a custom instance of prebuilt type validators using static methods of `link:../../jsdoc/module-vertx-web-api-contract-js_parameter_type_validator-ParameterTypeValidator.html[ParameterTypeValidator]` and then load it into `link:../../jsdoc/module-vertx-web-api-contract-js_http_request_validation_handler-HTTPRequestValidationHandler.html[HTTPRequestValidationHandler]` using functions ending with `WithCustomTypeValidator`
* You can create your own `ParameterTypeValidator` implementing `link:../../jsdoc/module-vertx-web-api-contract-js_parameter_type_validator-ParameterTypeValidator.html[ParameterTypeValidator]` interface

=== Handling parameters
Now you can handle parameter values:

[source,js]
----
`example65`
----

As you can see, every parameter is mapped in respective language objects. You can also get a json body:

[source,js]
----
`example66`
----