= Apex
:toc: left

Apex is a set of building blocks for building web applications with Vert.x.

Think of it as a Swiss Army Knife for building
modern, scalable, web apps.

Vert.x core provides a fairly low level set of functionality for handling HTTP, and for some applications
that will be sufficient.

Vert.x Apex builds on Vert.x core to provide a richer set of functionality for building real web applications, more
easily.

It's the successor to http://pmlopes.github.io/yoke/[Yoke] in Vert.x 2.x, and takes inspiration from projects such
as http://expressjs.com/[Express] in the Node.js world and http://www.sinatrarb.com/[Sinatra] in the Ruby world.

Apex is designed to be powerful, un-opionated and fully embeddable. You just use the parts you want and nothing more.
Apex is not a container.

You can use Apex to create classic server-side web applications, RESTful web applications, 'real-time' (server push)
web applications, or any other kind of web application you can think of. Apex doesn't care. It's up to you to chose
the type of app you prefer, not Apex.

Apex is a great fit for writing *RESTful HTTP micro-services*, but we don't *force* you to write apps like that.

Some of the key features of Apex include:

* Routing (based on method, path, etc)
* Regular expression pattern matching for paths
* Extraction of parameters from paths
* Content negotiation
* Request body handling
* Body size limits
* Cookie parsing and handling
* Multipart forms
* Multipart file uploads
* Sub routers
* Session support - both local (for sticky sessions) and clustered (for non sticky)
* CORS (Cross Origin Resource Sharing) support
* Error page handler
* Basic Authentication
* Redirect based authentication
* User/role/permission authorisation
* Favicon handling
* Template support for server side rendering, including support for the following template engines out of the box:
** Handlebars
** Jade,
** MVEL
** Thymeleaf
* Response time handler
* Static file serving, including caching logic and directory listing.
* Request timeout support

Most features in Apex are implemented as handlers so you can always write your own. We envisage many more being written
over time.

We'll discuss all these features in this manual.

== Re-cap on Vert.x core HTTP servers

Apex uses and exposes the API from Vert.x core, so it's well worth getting familiar with the basic concepts of writing
HTTP servers using Vert.x core, if you're not already.

The Vert.x core HTTP documentation goes into a lot of detail on this.

Here's a hello world web server written using Vert.x core. At this point there is no Apex involved:

[source,java]
----
def server = vertx.createHttpServer();
server.requestHandler({ request ->
  def response = request.response();
  response.putHeader("content-type", "text/plain");
  response.end("Hello World!");
});
server.listen(8080);

----

We create an HTTP server instance, and we set a request handler on it. The request handler will be called whenever
a request arrives on the server.

When that happens we are just going to set the content type to `text/plain`, and write `Hello World!` and end the
response.

We then tell the server to listen at port `8080` (default host is `localhost`).

You can run this, and point your browser at `http://localhost:8080` to verify that it works as expected.

== Basic Apex concepts

Here's the 10000 foot view:

A `link:groovydoc/io/vertx/groovy/ext/apex/Router.html[Router]` is one of the core concepts of Apex. It's an object which maintains zero or more
`link:groovydoc/io/vertx/groovy/ext/apex/Route.html[Routes]` .

A router takes an HTTP request and finds the first matching route for that request, and passes the request to that route.

The route can have a _handler_ associated with it, which then receives the request. You then _do something_ with the
request, and then, either end it or pass it to the next matching handler.

Here's a simple router example:

[source,java]
----
todo
----

It basically does the same thing as the Vert.x Core HTTP server hello world example from the previous section,
but this time using Apex.

We create an HTTP server as before, then we create a router. Once we've done that we create a simple route with
no matching criteria so it will match _all_ requests that arrive on the server.

We then specify a handler for that route. That handler will be called for all requests that arrive on the server.

The object that gets passed into the handler is a `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html[RoutingContext]` - this contains
the standard Vert.x `link:groovydoc/io/vertx/groovy/core/http/HttpServerRequest.html[HttpServerRequest]` and `link:groovydoc/io/vertx/groovy/core/http/HttpServerResponse.html[HttpServerResponse]`
but also various other useful stuff that makes working with Apex simpler.

For every request that is routed there is a unique routing context instance, and the same instance is passed to
all handlers for that request.

Once we've set up the handler, we set the request handler of the HTTP server to pass all incoming requests
to `link:groovydoc/io/vertx/groovy/ext/apex/Router.html#accept(io.vertx.core.http.HttpServerRequest)[accept]`.

So, that's the basics. Now we'll look at things in more detail:

== Handling requests and calling the next handler

When Apex decides to route a request to a matching route, it calls the handler of the route passing in an instance
of `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html[RoutingContext]`.

If you don't end the response in your handler, you should call `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#next()[next]` so another
matching route can handle the request (if any).

You don't have to call `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#next()[next]` before the handler has finished executing.
You can do this some time later, if you want:

[source,java]
----
def route1 = router.route("/some/path/").handler({ routingContext ->
  def response = routingContext.response();
  response.write("route1\n");
  routingContext.vertx().setTimer(5000, { tid ->
    routingContext.next()});
});
def route2 = router.route("/some/path/").handler({ routingContext ->
  def response = routingContext.response();
  response.write("route2\n");
  routingContext.vertx().setTimer(5000, { tid ->
    routingContext.next()});
});
def route3 = router.route("/some/path/").handler({ routingContext ->
  def response = routingContext.response();
  response.write("route3");
  routingContext.response().end();
});

----

In the above example `route1` is written to the response, then 5 seconds later `route2` is written to the response,
then 5 seconds later `route3` is written to the response and the response is ended.

Note, all this happens without any thread blocking.

== Routing by path

A route can be set-up to match the path from the request URI. In this case it will match any request which has a path
that _starts with_ the specified path.

In the following example the handler will be called for all requests with a URI path that starts with
`/some/path/`.

For example `/some/path/foo.html` and `/some/path/otherdir/blah.css` would both match.

[source,java]
----
def route = router.route().path("/some/path/");
route.handler({ routingContext ->
});

----

Alternatively the path can be specified when creating the route:

[source,java]
----
def route = router.route("/some/path/");
route.handler({ routingContext ->
});

----

== Capturing path parameters

It's possible to match paths using placeholders for parameters which are then available in the request
`link:groovydoc/io/vertx/groovy/core/http/HttpServerRequest.html#params()[params]`.

Here's an example

[source,java]
----
def route = router.route('POST', "/catalogue/products/:productype/:productid/");
route.handler({ routingContext ->
  def productType = routingContext.request().getParam("producttype");
  def productID = routingContext.request().getParam("productid");
});

----

The placeholders consist of `:` followed by the parameter name. Parameter names consist of any alphabetic character,
numeric character or underscore.

In the above example, if a POST request is made to path: `/catalogue/products/tools/drill123/` then the route will match
and `productType` will receive the value `tools` and productID will receive the value `drill123`.

== Routing with regular expressions

Regular expressions can also be used to match URI paths in routes.

As in straight path matching the regex is not an *exact match* for the path, but matches the start of the path.

[source,java]
----
def route = router.route().pathRegex(".*foo");
route.handler({ routingContext ->
});

----

Alternatively the regex can be specified when creating the route:

[source,java]
----
def route = router.routeWithRegex(".*foo");
route.handler({ routingContext ->
});

----

== Capturing path parameters with regular expressions

You can also capture path parameters when using regular expressions, here's an example:

[source,java]
----
def route = router.routeWithRegex(".*foo");
route.pathRegex("\\/([^\\/]+)\\/([^\\/]+)").handler({ routingContext ->
  def productType = routingContext.request().getParam("param0");
  def productID = routingContext.request().getParam("param1");
});

----

In the above example, if a request is made to path: `/tools/drill123/` then the route will match
and `productType` will receive the value `tools` and productID will receive the value `drill123`.

Captures are denoted in regular expressions with capture groups (i.e. surrounding the capture with round brackets)

== Routing by HTTP method

By default a route will match all HTTP methods.

If you want a route to only match for a specific HTTP method you can use `link:groovydoc/io/vertx/groovy/ext/apex/Route.html#method(io.vertx.core.http.HttpMethod)[method]`

[source,java]
----
def route = router.route().method('POST');
route.handler({ routingContext ->
});

----

Or you can specify this with a path when creating the route:

[source,java]
----
def route = router.route('POST', "/some/path/");
route.handler({ routingContext ->
});

----

If you want to route for a specific HTTP method you can also use the methods such as `link:groovydoc/io/vertx/groovy/ext/apex/Router.html#get()[get]`,
`link:groovydoc/io/vertx/groovy/ext/apex/Router.html#post()[post]` and `link:groovydoc/io/vertx/groovy/ext/apex/Router.html#put()[put]` named after the HTTP
method name. For example:

[source,java]
----
router.get().handler({ routingContext ->
});
router.get("/some/path/").handler({ routingContext ->
});
router.getWithRegex(".*foo").handler({ routingContext ->
});

----

If you want to specify a route will match for more than HTTP method you can call `link:groovydoc/io/vertx/groovy/ext/apex/Route.html#method(io.vertx.core.http.HttpMethod)[method]`
multiple times:

[source,java]
----
def route = router.route().method('POST').method('PUT');
route.handler({ routingContext ->
});

----

== Route order

By default routes are matched in the order they are added to the router.

When a request arrives the router will step through each route and check if it matches, if it matches then
the handler for that route will be called.

If the handler subsequently calls `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#next()[next]` the handler for the next
matching route (if any) will be called. And so on.

Here's an example to illustrate this:

[source,java]
----
def route1 = router.route("/some/path/").handler({ routingContext ->
  def response = routingContext.response();
  response.write("route1\n");
  routingContext.next();
});
def route2 = router.route("/some/path/").handler({ routingContext ->
  def response = routingContext.response();
  response.write("route2\n");
  routingContext.next();
});
def route3 = router.route("/some/path/").handler({ routingContext ->
  def response = routingContext.response();
  response.write("route3");
  routingContext.response().end();
});

----

In the above example the response will contain:

----
route1
route2
route3
----

As the routes have been called in that order for any request that starts with `/some/path`.

If you want to override the default ordering for routes, you can do so using `link:groovydoc/io/vertx/groovy/ext/apex/Route.html#order(int)[order]`,
specifying an integer value.

Routes are assigned an order at creation time corresponding to the order in which they were added to the router, with
the first route numbered `0`, the second route numbered `1`, and so on.

By specifying an order for the route you can override the default ordering. Order can also be negative, e.g. if you
want to ensure a route is evaluated before route number `0`.

Let's change the ordering of route2 so it runs before route1:

[source,java]
----
def route1 = router.route("/some/path/").handler({ routingContext ->
  def response = routingContext.response();
  response.write("route1\n");
  routingContext.next();
});
def route2 = router.route("/some/path/").handler({ routingContext ->
  def response = routingContext.response();
  response.write("route2\n");
  routingContext.next();
});
def route3 = router.route("/some/path/").handler({ routingContext ->
  def response = routingContext.response();
  response.write("route3");
  routingContext.response().end();
});
route2.order(-1);

----

then the response will now contain:

----
route2
route1
route3
----

If two matching routes have the same value of order, then they will be called in the order they were added.

You can also specify that a route is handled last, with `link:groovydoc/io/vertx/groovy/ext/apex/Route.html#last(boolean)[last]`

== Routing based on MIME type of request

You can specify that a route will match against matching request MIME types using `link:groovydoc/io/vertx/groovy/ext/apex/Route.html#consumes(java.lang.String)[consumes]`.

In this case, the request will contain a `content-type` header specifying the MIME type of the request body.
This will be matched against the value specified in `link:groovydoc/io/vertx/groovy/ext/apex/Route.html#consumes(java.lang.String)[consumes]`.

Basically, `consumes` is describing which MIME types the handler can _consume_.

Matching can be done on exact MIME type matches:

[source,java]
----
router.route().consumes("text/html").handler({ routingContext ->
});

----

Multiple exact matches can also be specified:

[source,java]
----
router.route().consumes("text/html").consumes("text/plain").handler({ routingContext ->
});

----

Matching on wildcards for the sub-type is supported:

[source,java]
----
router.route().consumes("text/*").handler({ routingContext ->
});

----

And you can also match on the top level type

[source,java]
----
router.route().consumes("*/json").handler({ routingContext ->
});

----

If you don't specify a `/` in the consumers, it will assume you meant the sub-type.

== Routing based on MIME types acceptable by the client

The HTTP `accept` header is used to signify which MIME types of the response are acceptable to the client.

An `accept` header can have multiple MIME types separated by '`,`'.

MIME types can also have a `q` value appended to them* which signifies a weighting to apply if more than one
response MIME type is available matching the accept header. The q value is a number between 0 and 1.0.
If omitted it defaults to 1.0.

For example, the following `accept` header signifies the client will accept a MIME type of only `text/plain`:

 Accept: text/plain

With the following the client will accept `text/plain` or `text/html` with no preference.

 Accept: text/plain, text/html

With the following the client will accept `text/plain` or `text/html` but prefers `text/html` as it has a higher
`q` value (the default value is q=1.0)

 Accept: text/plain; q=0.9, text/html

If the server can provide both text/plain and text/html it should provide the text/html in this case.

By using `link:groovydoc/io/vertx/groovy/ext/apex/Route.html#produces(java.lang.String)[produces]` you define which MIME type(s) the route produces, e.g. the
following handler produces a response with MIME type `application/json`.

[source,java]
----
router.route().produces("application/json").handler({ routingContext ->
  def response = routingContext.response();
  response.putHeader("content-type", "application/json");
  response.write(someJSON).end();
});

----

In this case the route will match with any request with an `accept` header that matches `application/json`.

Here are some examples of `accept` headers that will match:

 Accept: application/json
 Accept: application/*
 Accept: application/json, text/html
 Accept: application/json;q=0.7, text/html;q=0.8, text/plain

You can also mark your route as producing more than one MIME type. If this is the case, then you use
`link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#getAcceptableContentType()[getAcceptableContentType]` to find out the actual MIME type that
was accepted.

[source,java]
----
router.route().produces("application/json").produces("text/html").handler({ routingContext ->
  def response = routingContext.response();
  def acceptableContentType = routingContext.getAcceptableContentType();
  response.putHeader("content-type", acceptableContentType);
  response.write(whatever).end();
});

----

In the above example, if you sent a request with the following `accept` header:

 Accept: application/json; q=0.7, text/html

Then the route would match and `acceptableContentType` would contain `text/html` as both are
acceptable but that has a higher `q` value.

== Combining routing criteria

You can combine all the above routing criteria in many different ways, for example:

[source,java]
----
def route = router.route('PUT', "myapi/orders").consumes("application/json").produces("application/json");
route.handler({ routingContext ->
});

----

== Enabling and disabling routes

You can disable a route with `link:groovydoc/io/vertx/groovy/ext/apex/Route.html#disable()[disable]`. A disabled route will be ignored when matching.

You can re-enable a disabled route with `link:groovydoc/io/vertx/groovy/ext/apex/Route.html#enable()[enable]`

== Context data

You can use the context data in the `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html[RoutingContext]` to maintain any data that you
want to share between handlers for the lifetime of the request.

Here's an example where one handler sets some data in the context data and a subsequent handler retrieves it:

You can use the `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#put(java.lang.String,%20java.lang.Object)[put]` to put any object, and
`link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#get(java.lang.String)[get]` to retrieve any object from the context data.

A request sent to path `/some/path/other` will match both routes.

[source,java]
----
router.get("/some/path").handler({ routingContext ->
  routingContext.put("foo", "bar");
  routingContext.next();
});
router.get("/some/path/other").handler({ routingContext ->
  def bar = routingContext.get("foo");
  routingContext.response().end();
});

----

Alternatively you can access the entire context data map with `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#data()[data]`.

== Sub-routers

Sometimes if you have a lot of handlers it can make sense to split them up into multiple routers. This is also useful
if you want to reuse a set of handlers in a different application, rooted at a different path root.

To do this you can mount a router at a _mount point_ in another router. The router that is mounted is called a
_sub-router_. Sub routers can mount other sub routers so you can have several levels of sub-routers if you like.

Let's look at a simple example of a sub-router mounted with another router.

This sub-router will maintain the set of handlers that corresponds to a simple fictional REST API. We will mount that on another
router. The full implementation of the REST API is not shown.

Here's the sub-router:

[source,java]
----
import io.vertx.groovy.ext.apex.Router
def restAPI = Router.router(vertx);
restAPI.get("/products/:productID").handler({ rc ->
  rc.response().write(productJSON);
});
restAPI.put("/products/:productID").handler({ rc ->
  rc.response().end();
});
restAPI.delete("/products/:productID").handler({ rc ->
  rc.response().end();
});

----

If this router was used as a top level router, then GET/PUT/DELETE requests to urls like `/products/product1234`
would invoke the  API.

However, let's say we already have a web-site as described by another router:

[source,java]
----
import io.vertx.groovy.ext.apex.Router
def mainRouter = Router.router(vertx);
mainRouter.route("/static").handler(myStaticHandler);
mainRouter.route(".*\\.templ").handler(myTemplateHandler);

----

We can now mount the sub router on the main router, against a mount point, in this case `/productsAPI`

[source,java]
----
mainRouter.mountSubRouter("/productsAPI", restAPI);

----

This means the REST API is not accessible via paths like: `/productsAPI/products/product1234`

== Default 404 Handling

If no routes match for any particular request, Apex will signal a 404 error.

This can then be handled by your own error handler, or perhaps the augmented error handler that we supply to use,
or if no error handler is provided Apex will send back a basic 404 (Not Found) response.

== Error handling

As well as setting handlers to handle requests you can also set handlers to handle failures in routing.

Failure handlers are used with the exact same route matching criteria that you use with normal handlers.

For example you can provide a failure handler that will only handle failures on certain paths, or for certain HTTP methods.

This allows you to set different failure handlers for different parts of your application.

Here's an example failure handler that will only be called for failure that occur when routing to GET requests
to paths that start with `/somepath/`:

[source,java]
----
def route = router.get("/somepath/");
route.failureHandler({ frc ->
});

----

Failure routing will occur if a handler throws an exception, or if a handler calls
`link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#fail(int)[fail]` specifying an HTTP status code to deliberately signal a failure.

If an exception is caught from a handler this will result in a failure with status code `500` being signalled.

When handling the failure, the failure handler is passed the routing context which also allows the failure or failure code
to be retrieved so the failure handler can use that to generate a failure response.

[source,java]
----
todo
----

== Request body handling

The `link:groovydoc/io/vertx/groovy/ext/apex/handler/BodyHandler.html[BodyHandler]` allows you to retrieve request bodies, limit body sizes and handle
file uploads.

You should make sure a body handler is on a matching route for any requests that require this functionality.

[source,java]
----
import io.vertx.groovy.ext.apex.handler.BodyHandler
router.route().handler(BodyHandler.create());

----

=== Getting the request body

If you know the request body is JSON, then you can use `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#getBodyAsJson()[getBodyAsJson]`,
if you know it's a string you can use `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#getBodyAsString()[getBodyAsString]`, or to
retrieve it as a buffer use `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#getBody()[getBody]`.

=== Limiting body size

To limit the size of a request body, create the body handler with `link:groovydoc/io/vertx/groovy/ext/apex/handler/BodyHandler.html#create(long)[BodyHandler.create]`
specifying the maximum body size, in bytes. This is useful to avoid running out of memory with very large bodies.

If an attempt to send a body greater than the maximum size is made, an HTTP status code of 413 - `Request Entity Too Large`,
will be sent.

There is no body limit by default.

=== Handling file uploads

Body handler is also used to handle multi-part file uploads.

If a body handler is on a matching route for the request, any file uploads will be automatically streamed to the
uploads directory, which is `file-uploads` by default.

Each file will be given an automatically generated file name, and the file uploads will be available on the routing
context with `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#fileUploads()[fileUploads]`.

Here's an example:

[source,java]
----
import io.vertx.groovy.ext.apex.handler.BodyHandler
router.route().handler(BodyHandler.create());
router.post("/some/path/uploads").handler({ routingContext ->
  def uploads = routingContext.fileUploads();
});

----

Each file upload is described by a `link:groovydoc/io/vertx/groovy/ext/apex/FileUpload.html[FileUpload]` instance, which allows various properties
such as the name, file-name and size to be accessed.

== Handling cookies

Apex has cookies support using the `link:groovydoc/io/vertx/groovy/ext/apex/handler/CookieHandler.html[CookieHandler]`.

You should make sure a cookie handler is on a matching route for any requests that require this functionality.

[source,java]
----
import io.vertx.groovy.ext.apex.handler.CookieHandler
router.route().handler(CookieHandler.create());

----

=== Manipulating cookies

You use `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#getCookie(java.lang.String)[getCookie]` to retrieve
a cookie by name, or use `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#cookies()[cookies]` to retrieve the entire set.

To remove a cookie, use `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#removeCookie(java.lang.String)[removeCookie]`.

To add a cookie use `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#addCookie(io.vertx.ext.apex.Cookie)[addCookie]`.

The set of cookies will be written back in the response automatically when the response headers are written so the
browser can store them.

Cookies are described by instances of `link:groovydoc/io/vertx/groovy/ext/apex/Cookie.html[Cookie]`. This allows you to retrieve the name,
value, domain, path and other normal cookie properties.

Here's an example of querying and adding cookies:

[source,java]
----
import io.vertx.groovy.ext.apex.handler.CookieHandler
import io.vertx.groovy.ext.apex.Cookie
router.route().handler(CookieHandler.create());
router.route("some/path/").handler({ routingContext ->
  def someCookie = routingContext.getCookie("mycookie");
  def cookieValue = someCookie.getValue();
  routingContext.addCookie(Cookie.cookie("othercookie", "somevalue"));
});

----

== Handling sessions

Apex provides out of the box support for sessions.

Sessions last between HTTP requests for the length of a browser session and give you a place where you can add
session-scope information, such as a shopping basket.

Apex uses session cookies to identify a session. The session cookie is temporary and will be deleted by your browser
when it's closed.

We don't put the actual data of your session in the session cookie - the cookie simply uses an identifier to look-up
the actual session on the server. The identifier is a random UUID generated using a secure random, so it should
be effectively unguessable.

Cookies are passed across the wire in HTTP requests and responses so it's always wise to make sure you are using
HTTPS when sessions are being used. Vert.x will warn you if you attempt to use sessions over straight HTTP.

To enable sessions in your application you must have a `link:groovydoc/io/vertx/groovy/ext/apex/handler/SessionHandler.html[SessionHandler]`
on a matching route before your application logic.

The session handler handles the creation of session cookies and the lookup of the session so you don't have to do
that yourself.

=== Session stores

To create a session handler you need to have a session store instance. The session store is the object that
holds the actual sessions for your application.

Apex comes with two session store implementations out of the box, and you can also write your own if you prefer.

==== Local session store

With this store, sessions are stored locally in memory and only available in this instance.


This store is appropriate if you are using sticky sessions in your application and have configured your load balancer
(if you have one) to always route HTTP requests to the same Vert.x instance.

If you can't ensure your requests will all terminate on the same server then don't use this store as your
requests might end up on a server which doesn't know about your session.

Local session stores are implemented by using a shared local map, and have a reaper which clears out expired sessions.

The reaper period can be configured with
`link:groovydoc/io/vertx/groovy/ext/apex/sstore/LocalSessionStore.html#create(io.vertx.core.Vertx,%20java.lang.String,%20long)[LocalSessionStore.create]`.

Here are some examples of creating a `link:groovydoc/io/vertx/groovy/ext/apex/sstore/LocalSessionStore.html[LocalSessionStore]`

[source,java]
----
import io.vertx.groovy.ext.apex.sstore.LocalSessionStore
def store1 = LocalSessionStore.create(vertx);
def store2 = LocalSessionStore.create(vertx, "myapp3.sessionmap");
def store3 = LocalSessionStore.create(vertx, "myapp3.sessionmap", 10000);

----

==== Clustered session store

With this store, sessions are stored in a distributed map which is accessible across the Vert.x cluster.

This store is appropriate if you're _not_ using sticky sessions, i.e. your load balancer is distributing different
requests from the same browser to different servers.

Your session is accessible from any node in the cluster using this store.

To you use a clustered session store you should make sure your Vert.x instance is clustered.

Here are some examples of creating a `link:groovydoc/io/vertx/groovy/ext/apex/sstore/ClusteredSessionStore.html[ClusteredSessionStore]`

[source,java]
----
import io.vertx.groovy.core.Vertx
import io.vertx.groovy.ext.apex.sstore.ClusteredSessionStore
Vertx.clusteredVertx([
  clustered:true
], { res ->
  def vertx = res.result();
  def store1 = ClusteredSessionStore.create(vertx);
  def store2 = ClusteredSessionStore.create(vertx, "myclusteredapp3.sessionmap");
});

----

=== Creating the session handler

Once you've created a session store you can create a session handler, and add it to a route. You should make sure
your session handler is routed to before your application handlers.

You'll also need to include a `link:groovydoc/io/vertx/groovy/ext/apex/handler/CookieHandler.html[CookieHandler]` as the session handler uses cookies to
lookup the session. The cookie handler should be before the session handler when routing.

Here's an example:

[source,java]
----
import io.vertx.groovy.ext.apex.Router
import io.vertx.groovy.ext.apex.handler.CookieHandler
import io.vertx.groovy.ext.apex.sstore.ClusteredSessionStore
import io.vertx.groovy.ext.apex.handler.SessionHandler
def router = Router.router(vertx);
router.route().handler(CookieHandler.create());
def store = ClusteredSessionStore.create(vertx);
def sessionHandler = SessionHandler.create(store);
router.route().handler(sessionHandler);
router.route("/somepath/blah/").handler({ routingContext ->
  def session = routingContext.session();
  session.put("foo", "bar");
});

----

The session handler will ensure that your session is automatically looked up (or created if no session exists)
from the session store and set on the routing context before it gets to your application handlers.

=== Using the session

In your handlers you an access the session instance with `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#session()[session]`.

You put data into the session with `link:groovydoc/io/vertx/groovy/ext/apex/Session.html#put(java.lang.String,%20java.lang.Object)[put]`,
you get data from the session with `link:groovydoc/io/vertx/groovy/ext/apex/Session.html#get(java.lang.String)[get]`, and you remove
data from the session with `link:groovydoc/io/vertx/groovy/ext/apex/Session.html#remove(java.lang.String)[remove]`.

The keys for items in the session are always strings. The values can be any type for a local session store, and for
a clustered session store they can be any basic type, or `link:groovydoc/io/vertx/groovy/core/buffer/Buffer.html[Buffer]`, `link:groovydoc/io/vertx/groovy/core/json/JsonObject.html[JsonObject]`,
`link:groovydoc/io/vertx/groovy/core/json/JsonArray.html[JsonArray]` or a serializable object, as the values have to serialized across the cluster.

Here's an example of manipulating session data:

[source,java]
----
import io.vertx.groovy.ext.apex.handler.CookieHandler
router.route().handler(CookieHandler.create());
router.route().handler(sessionHandler);
router.route("/somepath/blah").handler({ routingContext ->
  def session = routingContext.session();
  session.put("foo", "bar");
  def age = session.get("age");
  def obj = session.remove("myobj");
});

----

Sessions are automatically written back to the store after after every response that has been routed through the
session handler has been written.

You can manually destroy a session using `link:groovydoc/io/vertx/groovy/ext/apex/Session.html#destroy()[destroy]`. This will remove the session
from the context and the session store. Note that if there is no session a new one will be automatically created
for the next request from the browser that's routed through the session handler.

== Authentication / authorisation

Vert.x comes with some out of the box handlers for handling both authentication (login) and authorisation (seeing
whether you have rights for some resource).

=== Creating an auth handler

To create an auth handler you need an instance of `link:groovydoc/io/vertx/groovy/ext/auth/AuthService.html[AuthService]`. Auth service is
(unsurprisingly) a Vert.x service that is used for authentication and authorisation of users. It uses a simple
role/permission model and, by default, is backed by Apache Shiro. For full information on the auth service and how
to use and configure it please consult the auth service documentation.

Like many services in Vert.x they can be instantiated locally, or you can create a proxy to an existing auth service
deployed as a verticle somewhere on the network. The latter case is useful if you have an app composed of many verticles
that want to do auth and you don't want each verticle to have its own auth service instance, or perhaps you have a single
auth service managed somewhere on your network and you want all auth request to go through that.

Here's a simple example of creating a basic auth service that gets user data from a properties file and creating
an auth handler from that, but it's the same principle whatever concrete auth service you use.

[source,java]
----
import io.vertx.groovy.ext.auth.AuthService
import io.vertx.groovy.ext.apex.handler.BasicAuthHandler
def config = [:];
config.io.vertx.ext.auth.PropertiesAuthRealmConstants.PROPERTIES_PROPS_PATH_FIELD = "classpath:test-auth.properties";
def authService = AuthService.create(vertx, config);
def basicAuthHandler = BasicAuthHandler.create(authService);

----

And here's an example of creating an auth service proxy to an existing auth service that is deployed elsewhere:

[source,java]
----
import io.vertx.groovy.ext.auth.AuthService
import io.vertx.groovy.ext.apex.handler.BasicAuthHandler
def authService = AuthService.createEventBusProxy(vertx, "acme.authservice");
def basicAuthHandler = BasicAuthHandler.create(authService);

----

You'll also need cookies and sessions enabled for auth handling to work:

[source,java]
----
import io.vertx.groovy.ext.apex.handler.CookieHandler
import io.vertx.groovy.ext.apex.handler.SessionHandler
import io.vertx.groovy.ext.apex.sstore.LocalSessionStore
import io.vertx.groovy.ext.auth.AuthService
import io.vertx.groovy.ext.apex.handler.BasicAuthHandler
router.route().handler(CookieHandler.create());
router.route().handler(SessionHandler.create(LocalSessionStore.create(vertx)));
def authService = AuthService.createEventBusProxy(vertx, "acme.authservice");
def basicAuthHandler = BasicAuthHandler.create(authService);

----

=== Handling auth in your application

Let's say you want all requests to paths that start with `/private/` to be subject to auth. To do that you make sure
your auth handler is before your application handlers on those paths:

[source,java]
----
import io.vertx.groovy.ext.apex.handler.CookieHandler
import io.vertx.groovy.ext.apex.handler.SessionHandler
import io.vertx.groovy.ext.apex.sstore.LocalSessionStore
import io.vertx.groovy.ext.auth.AuthService
import io.vertx.groovy.ext.apex.handler.BasicAuthHandler
router.route().handler(CookieHandler.create());
router.route().handler(SessionHandler.create(LocalSessionStore.create(vertx)));
def authService = AuthService.createEventBusProxy(vertx, "acme.authservice");
def basicAuthHandler = BasicAuthHandler.create(authService);
router.route("/private/").handler(basicAuthHandler);
router.route("/someotherpath").handler({ routingContext ->
});
router.route("/private/somepath").handler({ routingContext ->
  def isLoggedIn = routingContext.session().isLoggedIn();
});

----

If the auth handler has successfully authenticated and authorised the user it will set the principal (username) on the
session object, and the session will be marked as logged in. You can query the logged in status and get the
principal with `link:groovydoc/io/vertx/groovy/ext/apex/Session.html#isLoggedIn()[isLoggedIn]` and `link:groovydoc/io/vertx/groovy/ext/apex/Session.html#getPrincipal()[getPrincipal]`.

If you want to cause the user to be logged out you can call `link:groovydoc/io/vertx/groovy/ext/apex/Session.html#logout()[logout]`.

=== HTTP Basic Authentication

http://en.wikipedia.org/wiki/Basic_access_authentication[HTTP Basic Authentication] is a simple means of authentication
that can be appropriate for simple applications.

With basic auth, credentials are sent unencrypted across the wire in HTTP headers so it's essential that you serve
your application using HTTPS not HTTP.

With basic auth, if a user requests a resource that requires authorisation, the basic auth handler will send back
a `401` response with the header `WWW-Authenticate` set. This prompts the browser to show a log-in dialogue and
prompt the user to enter their username and password.

The request is made to the resource again, this time with the `Authorization` header set, containing the username
and password encoded in Base64.

When the basic auth handler receives this information, it calls the configured `link:groovydoc/io/vertx/groovy/ext/auth/AuthService.html[auth service]`
with the username and password to authenticate the user. If the authentication is successful the handler attempts
to authorise the user. If that is successful then the routing of the request is allowed to continue to the application
handlers, otherwise a `403` response is returned to signify that access is denied.

The auth handler can be set-up with a set of permissions and/or roles that are required for access to the resources to
be granted.

=== Redirect auth handler

With redirect auth handling the user is redirected to towards a login page in the case they are trying to access
a protected resource and they are not logged in.

The user then fills in the login form and submits it. This is handled by the server which authenticates
the user and, if authenticated redirects the user back to the original resource.

To use redirect auth you configure an instance of `link:groovydoc/io/vertx/groovy/ext/apex/handler/RedirectAuthHandler.html[RedirectAuthHandler]` instead of a
basic auth handler.

You will also need to setup handlers to serve your actual login page, and a handler to handle the actual login itself.
To handle the login we provide a prebuilt handler `link:groovydoc/io/vertx/groovy/ext/apex/handler/FormLoginHandler.html[FormLoginHandler]` for the purpose.

Here's an example of a simple app, using a redirect auth handler on the default redirect url `/loginpage`.

[source,java]
----
import io.vertx.groovy.ext.apex.handler.CookieHandler
import io.vertx.groovy.ext.apex.handler.SessionHandler
import io.vertx.groovy.ext.apex.sstore.LocalSessionStore
import io.vertx.groovy.ext.auth.AuthService
import io.vertx.groovy.ext.apex.handler.RedirectAuthHandler
import io.vertx.groovy.ext.apex.handler.FormLoginHandler
import io.vertx.groovy.ext.apex.handler.StaticHandler
router.route().handler(CookieHandler.create());
router.route().handler(SessionHandler.create(LocalSessionStore.create(vertx)));
def authService = AuthService.createEventBusProxy(vertx, "acme.authservice");
def redirectAuthHandler = RedirectAuthHandler.create(authService);
router.route("/private/").handler(redirectAuthHandler);
router.route("/login").handler(FormLoginHandler.create(authService));
router.route().handler(StaticHandler.create());
router.route("/someotherpath").handler({ routingContext ->
});
router.route("/private/somepath").handler({ routingContext ->
  def isLoggedIn = routingContext.session().isLoggedIn();
});

----

=== Configuring required roles and permissions

With any auth handler you can also configure required roles and permissions to access the resource.

By default, if no roles/permissions are configured then it is sufficient to be logged in to access the resource, otherwise
the user must be both logged in (authenticated) and have the required roles/permissions.

Here's an example of configuring an app so that different roles/permissions are required for different parts of the
app:

[source,java]
----
import io.vertx.groovy.ext.apex.handler.RedirectAuthHandler
def managerAuthHandler = RedirectAuthHandler.create(authService);
managerAuthHandler.addRole("manager").addRole("admin");
router.route("/private/managers").handler(managerAuthHandler);
def settingsAuthHandler = RedirectAuthHandler.create(authService);
settingsAuthHandler.addRole("admin");
router.route("/private/settings").handler(settingsAuthHandler);

----

=== OAuth

TODO

== Serving static resources

Apex comes with an out of the box handler for serving static web resources so you can write static web servers
very easily.

To serve static resources such as `.html`, `.css`, `.js` or any other static resource, you use an instance of
`link:groovydoc/io/vertx/groovy/ext/apex/handler/StaticHandler.html[StaticHandler]`.

Any requests to paths handled by the static handler will result in files being served from a directory on the file system
or from the classpath. The default static file directory is `webroot` but this can be configured.

In the following example all requests to paths starting with `/static/` will get served from the directory `webroot`:

[source,java]
----
import io.vertx.groovy.ext.apex.handler.StaticHandler
router.route("/static/").handler(StaticHandler.create());

----

For example, if there was a request with path `/static/css/mystyles.css` the static serve will look for a file in the
directory `webroot/static/css/mystyle.css`.

It will also look for a file on the classpath called `webroot/static/css/mystyle.css`. This means you can package up all your
static resources into a jar file (or fatjar) and distribute them like that.

When Vert.x finds a resource on the classpath for the first time it extracts it and caches it in a temporary directory
on disk so it doesn't have to do this each time.

=== Configuring caching

By default the static handler will set cache headers to enable browsers to effectively cache files.

Apex sets the headers `cache-control`,`last-modified`, and `date`.

`cache-control` is set to `max-age=86400` by default. This corresponds to one day. This can be configured with
`link:groovydoc/io/vertx/groovy/ext/apex/handler/StaticHandler.html#setMaxAgeSeconds(long)[setMaxAgeSeconds]` if required.

If a browser sends a GET or a HEAD request with an `if-modified-since` header and the resource has not been modified
since that date, a `304` status is returned which tells the browser to use its locally cached resource.

If handling of cache headers is not required, it can be disabled with `link:groovydoc/io/vertx/groovy/ext/apex/handler/StaticHandler.html#setCachingEnabled(boolean)[setCachingEnabled]`.

When cache handling is enabled Apex will cache the last modified date of resources in memory, this avoids a disk hit
to check the actual last modified date every time.

Entries in the cache have an expiry time, and after that time, the file on disk will be checked again and the cache
entry updated.

If you know that your files never change on disk, then the cache entry will effectively never expire. This is the
default.

If you know that your files might change on disk when the server is running then you can set files read only to false with
`link:groovydoc/io/vertx/groovy/ext/apex/handler/StaticHandler.html#setFilesReadOnly(boolean)[setFilesReadOnly]`.

To enable the maximum number of entries that can be cached in memory at any one time you can use
`link:groovydoc/io/vertx/groovy/ext/apex/handler/StaticHandler.html#setMaxCacheSize(int)[setMaxCacheSize]`.

To configure the expiry time of cache entries you can use `link:groovydoc/io/vertx/groovy/ext/apex/handler/StaticHandler.html#setCacheEntryTimeout(long)[setCacheEntryTimeout]`.

=== Configuring the index page

Any requests to the root path `/` will cause the index page to be served. By default the index page is `index.html`.
This can be configured with `link:groovydoc/io/vertx/groovy/ext/apex/handler/StaticHandler.html#setIndexPage(java.lang.String)[setIndexPage]`.

=== Changing the web root

By default static resources will be served from the directory `webroot`. To configure this use
`link:groovydoc/io/vertx/groovy/ext/apex/handler/StaticHandler.html#setWebRoot(java.lang.String)[setWebRoot]`.

=== Serving hidden files

By default the serve will serve hidden files (files starting with `.`).

If you do not want hidden files to be served you can configure it with `link:groovydoc/io/vertx/groovy/ext/apex/handler/StaticHandler.html#setIncludeHidden(boolean)[setIncludeHidden]`.

=== Directory listing

The server can also perform directory listing. By default directory listing is disabled. To enabled it use
`link:groovydoc/io/vertx/groovy/ext/apex/handler/StaticHandler.html#setDirectoryListing(boolean)[setDirectoryListing]`.

When directory listing is enabled the content returned depends on the content type in the `accept` header.

For `text/html` directory listing, the template used to render the directory listing page can be configured with
`link:groovydoc/io/vertx/groovy/ext/apex/handler/StaticHandler.html#setDirectoryTemplate(java.lang.String)[setDirectoryTemplate]`.

== CORS handling

http://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross Origin Resource Sharing] is a safe mechanism for
allowing resources to be requested from one domain and served from another.

Apex includes a handler `link:groovydoc/io/vertx/groovy/ext/apex/handler/CorsHandler.html[CorsHandler]` that handles the CORS protocol for you.

Here's an example:

[source,java]
----
import io.vertx.groovy.ext.apex.handler.CorsHandler
router.route().handler(CorsHandler.create("vertx\\.io").allowedMethod('GET'));
router.route().handler({ routingContext ->
});

----

TODO more CORS docs

== Templates

Apex includes dynamic page generation capabilities by including out of the box support for several popular template
engines. You can also easily add your own.

Template engines are described by `link:groovydoc/io/vertx/groovy/ext/apex/templ/TemplateEngine.html[TemplateEngine]`. In order to render a template
`link:groovydoc/io/vertx/groovy/ext/apex/templ/TemplateEngine.html#render(io.vertx.ext.apex.RoutingContext,%20java.lang.String,%20io.vertx.core.Handler)[render]` is used.

The simplest way to use templates is not to call the template engine directly but to use the
`link:groovydoc/io/vertx/groovy/ext/apex/handler/TemplateHandler.html[TemplateHandler]`.
This handler calls the template engine for you based on the path in the HTTP request.

By default the template handler will look for templates in a directory called `templates`. This can be configured.

The handler will return the results of rendering with a content type of `text/html` by default. This can also be configured.

When you create the template handler you pass in an instance of the template engine you want.

Here are some examples

[source,java]
----
import io.vertx.groovy.ext.apex.templ.HandlebarsTemplateEngine
import io.vertx.groovy.ext.apex.handler.TemplateHandler
def engine = HandlebarsTemplateEngine.create();
def handler = TemplateHandler.create(engine);
router.get("/dynamic/").handler(handler);
router.getWithRegex(".+\\.hbs").handler(handler);

----

=== MVEL template engine

When using the `link:groovydoc/io/vertx/groovy/ext/apex/templ/MVELTemplateEngine.html[MVEL template engine]`, it will by default look for
templates with the `.templ` extension if no extension is specified in the file name.

The routing context `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html[RoutingContext]` is available
in the MVEL template as the `context` variable, this means you can render the template based on anything in the context
including the request, response, session or context data.

Here are some examples:

----
The request path is @{context.request().path()}

The variable 'foo' from the session is @{context.session().get('foo')}

The value 'bar' from the context data is @{context.get('bar')}
----

Please consult the http://mvel.codehaus.org/MVEL+2.0+Templating+Guide[MVEL templates documentation] for how to write
MVEL templates.

=== Jade template engine

When using the `link:groovydoc/io/vertx/groovy/ext/apex/templ/JadeTemplateEngine.html[Jade template engine]`, it will by default look for
templates with the `.jade` extension if no extension is specified in the file name.

The routing context `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html[RoutingContext]` is available
in the Jade template as the `context` variable, this means you can render the template based on anything in the context
including the request, response, session or context data.

Here are some examples:

----
!!! 5
html
  head
    title= context.get('foo') + context.request().path()
  body
----

Please consult the https://github.com/neuland/jade4j[Jade4j documentation] for how to write
Jade templates.

=== Handlebars template engine

When using the `link:groovydoc/io/vertx/groovy/ext/apex/templ/HandlebarsTemplateEngine.html[Handlebars template engine]`, it will by default look for
templates with the `.hbs` extension if no extension is specified in the file name.

Handlebars templates are not able to call arbitrary methods in objects so we can't just pass the routing context
into the template and let the template introspect it like we can with other template engines.

Instead, the context `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html#data()[data]` is available in the template.

If you want to have access to other data like the request path, request params or session data you should
add it the context data in a handler before the template handler. For example:

[source,java]
----
import io.vertx.groovy.ext.apex.templ.HandlebarsTemplateEngine
import io.vertx.groovy.ext.apex.handler.TemplateHandler
def engine = HandlebarsTemplateEngine.create();
def handler = TemplateHandler.create(engine);
router.get("/dynamic").handler({ routingContext ->
  routingContext.put("request_path", routingContext.request().path());
  routingContext.put("session_data", routingContext.session().data());
  routingContext.next();
});
router.get("/dynamic/").handler(handler);

----

Please consult the https://github.com/jknack/handlebars.java[Handlebars Java port documentation] for how to write
handlebars templates.

=== Thymeleaf template engine

When using the `link:groovydoc/io/vertx/groovy/ext/apex/templ/ThymeleafTemplateEngine.html[Thymeleaf template engine]`, it will by default look for
templates with the `.html` extension if no extension is specified in the file name.

The routing context `link:groovydoc/io/vertx/groovy/ext/apex/RoutingContext.html[RoutingContext]` is available
in the Thymeleaf template as the `context` variable, this means you can render the template based on anything in the context
including the request, response, session or context data.

Here are some examples:

----
[snip]
p th:text="${context.get('foo')}"/p
p th:text="${context.get('bar')}"/p
p th:text="${context.normalisedPath()}"/p
p th:text="${context.request().params().get('param1')}"/p
p th:text="${context.request().params().get('param2')}"/p
[snip]
----

Please consult the http://www.thymeleaf.org/[Thymeleaf documentation] for how to write
Thymeleaf templates.

== Error handler

You can render your own errors using a template handler or otherwise but Apex also includes an out of the boxy
"pretty" error handler that can render error pages for you.

The handler is `link:groovydoc/io/vertx/groovy/ext/apex/handler/ErrorHandler.html[ErrorHandler]`. To use the error handler just set it as a
failure handler for any paths that you want covered.

== Request logger

Apex includes a handler `link:groovydoc/io/vertx/groovy/ext/apex/handler/LoggerHandler.html[LoggerHandler]` that you can use to log HTTP requests.


By default requests are logged to the Vert.x logger which can be configured to use JUL logging, log4j or SLF4J.

== Serving favicons

Apex includes the handler `link:groovydoc/io/vertx/groovy/ext/apex/handler/FaviconHandler.html[FaviconHandler]` especially for serving favicons.

Favicons can be specified using a path to the filesystem, or by default Apex will look for a file on the classpath
with the name `favicon.ico`. This means you bundle the favicon in the jar of your application.

== Timeout handler

Apex includes a timeout handler that you can use to timeout requests if they take too long to process.

This is configured using an instance of `link:groovydoc/io/vertx/groovy/ext/apex/handler/TimeoutHandler.html[TimeoutHandler]`.

If a request times out before the response is written a `408` response will be returned to the client.

Here's an example of using a timeout handler which will timeout all requests to paths starting with `/foo` after 5
seconds:

[source,java]
----
import io.vertx.groovy.ext.apex.handler.TimeoutHandler
router.route("/foo/").handler(TimeoutHandler.create(5000));

----

== Response time handler

This handler sets the header `x-response-time` response header containing the time from when the request was received
to when the response headers were written, in ms., e.g.:

 x-response-time: 1456ms