= Vert.x-Web API Contract
:toc: left

== OpenAPI 3 support

Vert.x allows you to use your OpenApi 3 specification directly inside your code using the design first approach.

Vert.x-Web provides:

* OpenAPI 3 compliant API specification validation with automatic **loading of external Json schemas**
* Automatic request validation
* Automatic mount of security validation handlers
* Automatic 501 response for not implemented operations
* Router factory to provide all these features to users

=== The router factory
You can create your web service based on OpenAPI3 specification with `link:../../apidocs/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactory.html[OpenAPI3RouterFactory]`.
This class, as name says, is a router factory based on your OpenAPI 3 specification.
`link:../../apidocs/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactory.html[OpenAPI3RouterFactory]` is intended to give you a really simple user interface to use OpenAPI 3 support. It includes:

* Async loading of specification and its schema dependencies
* Mount path with operationId or with combination of path and HTTP method
* Automatic request parameters validation
* Automatic convert OpenAPI style paths to Vert.x style paths
* Lazy methods: operations (combination of paths and HTTP methods) are mounted in declaration order inside specification
* Automatic mount of security validation handlers

=== Create a new router factory
To create a new router factory, you can use methods inside `link:../../apidocs/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactory.html[OpenAPI3RouterFactory]`:

* `link:../../apidocs/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactory.html#createRouterFactoryFromFile-io.vertx.core.Vertx-java.lang.String-io.vertx.core.Handler-[OpenAPI3RouterFactory.createRouterFactoryFromFile]`  to create a router factory from local file
* `link:../../apidocs/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactory.html#createRouterFactoryFromURL-io.vertx.core.Vertx-java.lang.String-io.vertx.core.Handler-[OpenAPI3RouterFactory.createRouterFactoryFromURL]`  to create a router factory from url

For example:
[source,kotlin]
----
OpenAPI3RouterFactory.createRouterFactoryFromFile(vertx, "src/main/resources/petstore.yaml", { ar ->
  if (ar.succeeded()) {
    // Spec loaded with success
    var routerFactory = ar.result()
  } else {
    // Something went wrong during router factory initialization
    var exception = ar.cause()
  }
})

----

=== Mount the handlers
Now load your first path. There are two functions to load the handlers:

* `link:../../apidocs/io/vertx/ext/web/api/contract/DesignDrivenRouterFactory.html#addHandler-io.vertx.core.http.HttpMethod-java.lang.String-io.vertx.core.Handler-[addHandler]`
* `link:../../apidocs/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactory.html#addHandlerByOperationId-java.lang.String-io.vertx.core.Handler-[addHandlerByOperationId]`

And, of course, two functions to load failure handlers

* `link:../../apidocs/io/vertx/ext/web/api/contract/DesignDrivenRouterFactory.html#addFailureHandler-io.vertx.core.http.HttpMethod-java.lang.String-io.vertx.core.Handler-[addFailureHandler]`
* `link:../../apidocs/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactory.html#addFailureHandlerByOperationId-java.lang.String-io.vertx.core.Handler-[addFailureHandlerByOperationId]`

You can, of course, **add multiple handlers to same operation**, without overwrite the existing ones.

.Path in OpenAPI format
IMPORTANT: If you want to use `link:../../apidocs/io/vertx/ext/web/api/contract/DesignDrivenRouterFactory.html#addHandler-io.vertx.core.http.HttpMethod-java.lang.String-io.vertx.core.Handler-[addHandler]` or `link:../../apidocs/io/vertx/ext/web/api/contract/DesignDrivenRouterFactory.html#addFailureHandler-io.vertx.core.http.HttpMethod-java.lang.String-io.vertx.core.Handler-[addFailureHandler]` pay attention: You can provide a path only in OpenAPI styles (for example path `/hello/:param` doesn't work)

For example:
[source,kotlin]
----
routerFactory.addHandlerByOperationId("awesomeOperation", { routingContext ->
  var params = routingContext.get<Any>("parsedParameters")
  var body = params.body()
  var jsonBody = body.getJsonObject()
  // Do something with body
})
routerFactory.addFailureHandlerByOperationId("awesomeOperation", { routingContext ->
  // Handle failure
})

----

.Add operations with operationId
IMPORTANT: Usage of combination of path and HTTP method is allowed, but it's better to add operations handlers with operationId, for performance reasons and to avoid paths nomenclature errors

Now you can use parameter values as described in http://vertx.io/docs/vertx-web/java/#_andling_parameters[vertx-web documentation]

== Define security handlers
A security handler is defined by a combination of schema name and scope. You can mount only one security handler for a combination.
For example:

[source,kotlin]
----
routerFactory.addSecurityHandler("security_scheme_name", securityHandler)

----

You can of course use included Vert.x security handlers, for example:

[source,kotlin]
----
routerFactory.addSecurityHandler("jwt_auth", JWTAuthHandler.create(jwtAuthProvider))

----

=== Error handling
The router factory allows you to manage errors efficiently:

* It automatically mounts a 501 `Not Implemented` handler for operations where you haven't mounted any handler
* It automatically mounts a 400 `Bad Request` handler that manages `ValidationException` (You can enable/disable this feature via `link:../../apidocs/io/vertx/ext/web/api/contract/DesignDrivenRouterFactory.html#enableValidationFailureHandler-boolean-[enableValidationFailureHandler]`)

=== Generate the router
When you are ready, generate the router and use it:

[source,kotlin]
----
var router = routerFactory.getRouter()

var server = vertx.createHttpServer(HttpServerOptions(
  port = 8080,
  host = "localhost"))
server.requestHandler({ router.accept(it) }).listen()

----

== Requests validation

Vert.x provides a validation framework that will validate requests for you and will put results of validation inside a container. To define a `link:../../apidocs/io/vertx/ext/web/api/validation/HTTPRequestValidationHandler.html[HTTPRequestValidationHandler]`:
[source,kotlin]
----
// Create Validation Handler with some stuff
var validationHandler = HTTPRequestValidationHandler.create().addQueryParam("parameterName", ParameterType.INT, true).addFormParamWithPattern("formParameterName", "a{4}", true).addPathParam("pathParam", ParameterType.FLOAT)

----

Then you can mount your validation handler:
[source,kotlin]
----
// BodyHandler is required to manage body parameters like forms or json body
router.route().handler(BodyHandler.create())

router.get("/awesome/:pathParam").handler(validationHandler).handler({ routingContext ->
  // Get Request parameters container
  var params = routingContext.get<Any>("parsedParameters")

  // Get parameters
  var parameterName = params.queryParameter("parameterName").getInteger()
  var formParameterName = params.formParameter("formParameterName").getString()
  var pathParam = params.pathParameter("pathParam").getFloat()
}).failureHandler({ routingContext ->
  var failure = routingContext.failure()
  if (failure is io.vertx.ext.web.api.validation.ValidationException) {
    // Something went wrong during validation!
    var validationErrorMessage = failure.getMessage()
  }
})

----

If validation succeeds, It returns request parameters inside `link:../../apidocs/io/vertx/ext/web/api/RequestParameters.html[RequestParameters]`, otherwise It will throw a `link:../../apidocs/io/vertx/ext/web/api/validation/ValidationException.html[ValidationException]`

=== Types of request parameters
Every parameter has a type validator, a class that describes the expected type of parameter.
A type validator validates the value, casts it in required language type and then loads it inside a `link:../../apidocs/io/vertx/ext/web/api/RequestParameter.html[RequestParameter]` object. There are three ways to describe the type of your parameter:

* There is a set of prebuilt types that you can use: `link:../../apidocs/io/vertx/ext/web/api/validation/ParameterType.html[ParameterType]`
* You can instantiate a custom instance of prebuilt type validators using static methods of `link:../../apidocs/io/vertx/ext/web/api/validation/ParameterTypeValidator.html[ParameterTypeValidator]` and then load it into `link:../../apidocs/io/vertx/ext/web/api/validation/HTTPRequestValidationHandler.html[HTTPRequestValidationHandler]` using functions ending with `WithCustomTypeValidator`
* You can create your own `ParameterTypeValidator` implementing `link:../../apidocs/io/vertx/ext/web/api/validation/ParameterTypeValidator.html[ParameterTypeValidator]` interface

=== Handling parameters
Now you can handle parameter values:

[source,kotlin]
----
var params = routingContext.get<Any>("parsedParameters")
var awesomeParameter = params.queryParameter("awesomeParameter")
if (awesomeParameter != null) {
  if (!awesomeParameter.isEmpty()) {
    // Parameter exists and isn't empty
    // ParameterTypeValidator mapped the parameter in equivalent language object
    var awesome = awesomeParameter.getInteger()
  } else {
    // Parameter exists, but it's empty
  }
} else {
  // Parameter doesn't exist (it's not required)
}

----

As you can see, every parameter is mapped in respective language objects. You can also get a json body:

[source,kotlin]
----
var body = params.body()
if (body != null) {
  var jsonBody = body.getJsonObject()
}

----