name: Verify stack libraries version consistency

on:
  pull_request:
    branches: [ 'master', '3.*' ]
    paths:
      - '**/pom.xml'

jobs:
  test:
    name: Verify stack libraries version consistency
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo code
        uses: actions/checkout@v2
        with:
          path: this_repo

      - name: Check out vertx-stack
        uses: actions/checkout@v2
        with:
          repository: vert-x3/vertx-stack
          path: stack
          ref: ${{ github.base_ref }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install new snapshot of this repo
        run: mvn install -DskipTests --file this_repo/pom.xml --no-transfer-progress

      - name: Verify stack
        run: mvn verify --file stack/pom.xml --no-transfer-progress -am -pl stack-manager
